### ISSUE TITLE
Cannot find module 'react-sortable-tree'

### ISSUE THREAD

**Issue by antmanler** [GenesisKernel/genesis-front#26]
Following the doc, `yarn start` logs that error

![image](https://user-images.githubusercontent.com/354668/35955758-6658ab82-0ccc-11e8-8c43-85e22597f6c0.png)

**Comment by Saurer** [comment]
Hello, @antmanler 

This is a known problem that was recently fixed. Please update your repository to the latest version using "git pull"
Don't forget to "yarn install" again, so the project will be able to catch newly added dependencies

Feel free to ask again if the problem was not resolved

**Comment by antmanler** [comment]
I switched from GenesisCommunity to GenesisKernel, and it worked, thx
